server:
  port: 9000

logging:
  level:
    root: info

management:
  endpoint:
    health:
      show-detail: always
      show-components: always

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/widgetdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

flyway:
  enabled: true
  locations: classpath:db/migration
